-- vim.api.nvim_create_autocmd("FileType", {
--     pattern = "sql",
--     callback = function()
--         vim.opt.foldmethod = 'indent'
--         vim.opt_local.shiftwidth = 2
--         vim.opt_local.tabstop = 2
--     end
-- })
